local inspect = require("inspect")
require("init")

local linked_list = require("linked_list")

-- following to disable warning for assert.are checks
--- @diagnostic disable: undefined-field

local node1, node2, node3
describe("linked_list.length()", function()
	before_each(function()
		linked_list.new()
		node1 = linked_list.new_node("ONE")
		node2 = linked_list.new_node("TWO")
		node3 = linked_list.new_node("THREE")
	end)
	it("empty list length is 0 ", function()
		assert.are.equal(0, linked_list.length())
	end)
	it("one item in list length is 1", function()
		linked_list.push(node1)
		assert.are.equal(1, linked_list.length())
	end)
	it("two items in list length is 2", function()
		linked_list.push(node1)
		linked_list.push(node2)
		assert.are.equal(2, linked_list.length())
	end)
	it("three items in list length is 3", function()
		linked_list.push(node1)
		linked_list.push(node2)
		linked_list.push(node3)
		assert.are.equal(3, linked_list.length())
	end)
end)
