local inspect = require("inspect")
require("init")
local constants = require("constants")

local linked_list = require("linked_list")

-- following to disable warning for assert.are checks
--- @diagnostic disable: undefined-field

local node1, node2, node3
local function nodes_length(nodes)
	local length = 0
	for _, _ in pairs(nodes) do
		length = length + 1
	end
	return length
end
describe("linked_list.push(node)", function()
	before_each(function()
		linked_list.new()
		node1 = linked_list.new_node("ONE")
		node2 = linked_list.new_node("TWO")
		node3 = linked_list.new_node("THREE")
	end)
	it("add one item to empty list", function()
		linked_list.push(node1)
		assert.are.equal(1, nodes_length(linked_list.nodes), constants.EXPECTED_LENGTH)
		assert.is_true(linked_list.head == node1.address, constants.EXPECTED_HEAD)
		assert.is_true(node1.next == nil, constants.EXPECTED_NEXT)
	end)
	it("add two items to list", function()
		linked_list.push(node1)
		linked_list.push(node2)
		assert.are.equal(2, nodes_length(linked_list.nodes), constants.EXPECTED_LENGTH)
		assert.is_true(linked_list.head == node2.address, constants.EXPECTED_HEAD)
		assert.is_true(node2.next == node1.address, constants.EXPECTED_NEXT)
		assert.is_true(node1.next == nil, constants.EXPECTED_NEXT)
	end)
	it("add three items to list", function()
		linked_list.push(node1)
		linked_list.push(node2)
		linked_list.push(node3)
		assert.are.equal(3, nodes_length(linked_list.nodes), constants.EXPECTED_LENGTH)
		assert.is_true(linked_list.head == node3.address, constants.EXPECTED_HEAD)
		assert.is_true(node3.next == node2.address, constants.EXPECTED_NEXT)
		assert.is_true(node2.next == node1.address, constants.EXPECTED_NEXT)
		assert.is_true(node1.next == nil, constants.EXPECTED_NEXT)
	end)
end)
-- insert_at_head calls push
describe("linked_list.insert_at_head(node)", function()
	before_each(function()
		linked_list.new()
		node1 = linked_list.new_node("ONE")
		node2 = linked_list.new_node("TWO")
		node3 = linked_list.new_node("THREE")
	end)
	it("add one item to empty list", function()
		linked_list.insert_at_head(node1)
		assert.are.equal(1, nodes_length(linked_list.nodes), constants.EXPECTED_LENGTH)
		assert.is_true(linked_list.head == node1.address, constants.EXPECTED_HEAD)
		assert.is_true(node1.next == nil, constants.EXPECTED_NEXT)
	end)
	it("add two items to list", function()
		linked_list.insert_at_head(node1)
		linked_list.insert_at_head(node2)
		assert.are.equal(2, nodes_length(linked_list.nodes), constants.EXPECTED_LENGTH)
		assert.is_true(linked_list.head == node2.address, constants.EXPECTED_HEAD)
		assert.is_true(node2.next == node1.address, constants.EXPECTED_NEXT)
		assert.is_true(node1.next == nil, constants.EXPECTED_NEXT)
	end)
	it("add three items to list", function()
		linked_list.insert_at_head(node1)
		linked_list.insert_at_head(node2)
		linked_list.insert_at_head(node3)
		assert.are.equal(3, nodes_length(linked_list.nodes), constants.EXPECTED_LENGTH)
		assert.is_true(linked_list.head == node3.address, constants.EXPECTED_HEAD)
		assert.is_true(node3.next == node2.address, constants.EXPECTED_NEXT)
		assert.is_true(node2.next == node1.address, constants.EXPECTED_NEXT)
		assert.is_true(node1.next == nil, constants.EXPECTED_NEXT)
	end)
end)
