require("init")
local constants = require("constants")
local mocks = require("mocks")

local linked_list = require("linked_list")

-- following to disable warning for assert.are checks
--- @diagnostic disable: undefined-field

describe("linked_list.pop()", function()
	describe("empty list", function()
		before_each(function()
			linked_list.new()
			local head, nodes = mocks.empty_list()
			linked_list.head = head
			linked_list.nodes = nodes
		end)
		it("empty list returns nil", function()
			local node = linked_list.pop()
			assert.is_nil(node, constants.EXPECTED_NODE)
		end)
	end)

	describe("one item list", function()
		before_each(function()
			linked_list.new()
			local head, nodes = mocks.one_item_list()
			linked_list.head = head
			linked_list.nodes = nodes
		end)
		it("first node returned", function()
			local value = linked_list.pop()
			assert.are.equal(mocks.node1.value, value, constants.EXPECTED_NODE)
		end)
		it("head is nil", function()
			local _ = linked_list.pop()
			assert.is_nil(linked_list.head, constants.EXPECTED_HEAD)
		end)
		it("length is 0", function()
			local _ = linked_list.pop()
			assert.are.equal(0, linked_list.length(), constants.EXPECTED_LENGTH)
		end)
	end)
	describe("two item list", function()
		before_each(function()
			linked_list.new()
			local head, nodes = mocks.two_item_list()
			linked_list.head = head
			linked_list.nodes = nodes
		end)
		it("first node returned", function()
			local value = linked_list.pop()
			assert.are.equal(mocks.node1.value, value, constants.EXPECTED_NODE)
		end)
		it("head is node2", function()
			local _ = linked_list.pop()
			assert.are.equal(mocks.node2.address, linked_list.head, constants.EXPECTED_HEAD)
		end)
		it("length is 1", function()
			local _ = linked_list.pop()
			assert.are.equal(1, linked_list.length(), constants.EXPECTED_LENGTH)
		end)
	end)

	describe("three item list", function()
		before_each(function()
			linked_list.new()
			local head, nodes = mocks.three_item_list()
			linked_list.head = head
			linked_list.nodes = nodes
		end)
		it("first node returned", function()
			local value = linked_list.pop()
			assert.are.equal(mocks.node1.value, value, constants.EXPECTED_NODE)
		end)
		it("head is node2", function()
			local _ = linked_list.pop()
			assert.are.equal(mocks.node2.address, linked_list.head, constants.EXPECTED_HEAD)
		end)
		it("length is 2", function()
			local _ = linked_list.pop()
			assert.are.equal(2, linked_list.length(), constants.EXPECTED_LENGTH)
		end)
	end)
end)
