describe("Assertion examples", function()
	it("demonstrates various assertions", function()
		assert.are.equal(expected, actual)
		assert.are.same({ 1, 2 }, { 1, 2 }) -- Deep equality
		assert.is_true(value)
		assert.is_false(value)
		assert.is_nil(value)
		assert.is_not_nil(value)
		assert.has_error(function()
			error("boom")
		end)
		assert.has_no.errors(function()
			return true
		end)
	end)
end)

local User = require("user")

describe("User", function()
	describe("creation", function()
		it("should create user with valid data", function()
			local user = User.new("Alice", "alice@example.com")
			assert.is_not_nil(user)
		end)

		it("should reject invalid email", function()
			local user = User.new("Alice", "invalid-email")
			assert.is_nil(user)
		end)
	end)

	describe("authentication", function()
		describe("with valid credentials", function()
			it("should authenticate successfully", function()
				local user = User.new("Alice", "alice@example.com")
				user:set_password("secret123")
				assert.is_true(user:authenticate("secret123"))
			end)
		end)

		describe("with invalid credentials", function()
			it("should reject incorrect password", function()
				local user = User.new("Alice", "alice@example.com")
				user:set_password("secret123")
				assert.is_false(user:authenticate("wrong"))
			end)
		end)
	end)
end)
